# pacconf
# Autogenerated from man page /usr/share/man/man1/pacconf.1.gz
complete -c pacconf -l config -d 'Set an alternate configuration file path'
complete -c pacconf -l root -d 'Set an alternate installation root'
complete -c pacconf -l sysroot -d 'Set an alternate system root.   See pacutils-sysroot\\|(7)'
complete -c pacconf -l arch -d 'Set an alternate architecture'
complete -c pacconf -l null -d 'Set an alternate separator for values parsed from stdin'
complete -c pacconf -l options -d 'Only display global settings from the \\f(CW\\*(C`[options]\\*(C\' section'
complete -c pacconf -l raw -d 'Display unmodified values'
complete -c pacconf -l repo -d 'Only display directives for repository name'
complete -c pacconf -l repo-list -d 'List configured repositories'
complete -c pacconf -l single -d 'Display only first value of multi-value options'
complete -c pacconf -l verbose -d 'Always show directive names even if only one directive is provided'
complete -c pacconf -l help -d 'Display usage information and exit'

