# pacfile
# Autogenerated from man page /usr/share/man/man1/pacfile.1.gz
complete -c pacfile -l config -d 'Set an alternate configuration file path'
complete -c pacfile -l dbpath -d 'Set an alternate database path'
complete -c pacfile -l root -d 'Set an alternate installation root'
complete -c pacfile -l sysroot -d 'Set an alternate system root.   See pacutils-sysroot\\|(7)'
complete -c pacfile -l package -d 'Limit information to the specified package.   May be specified multiple times'
complete -c pacfile -l check -d 'Compare database values to the file system'
complete -c pacfile -l help -d 'Display usage information and exit'

