# pacini
# Autogenerated from man page /usr/share/man/man1/pacini.1.gz
complete -c pacini -l section -d 'Only display directives listed in section name'
complete -c pacini -l section-list -d 'List configured sections'
complete -c pacini -l verbose -d 'Always show directive names even if only one directive is provided'
complete -c pacini -l help -d 'Display usage information and exit'

