# pacinfo
# Autogenerated from man page /usr/share/man/man1/pacinfo.1.gz
complete -c pacinfo -l config -d 'Set an alternate configuration file path'
complete -c pacinfo -l dbext -d 'Set an alternate sync database extension'
complete -c pacinfo -l dbpath -d 'Set an alternate database path'
complete -c pacinfo -l root -d 'Set an alternate installation root'
complete -c pacinfo -l sysroot -d 'Set an alternate system root.   See pacutils-sysroot\\|(7)'
complete -c pacinfo -l null -d 'Set an alternate separator for values parsed from stdin'
complete -c pacinfo -l no-timeout -d 'Disable low-speed timeouts for downloads'
complete -c pacinfo -l short -d 'Display brief information'
complete -c pacinfo -l verbose -d 'Display additional package information: \\f(CW\\*(C`required by\\*(C\', \\f(CW\\*(C…'
complete -c pacinfo -l raw -d 'Display raw numeric size and date values'
complete -c pacinfo -l removable-size -d 'Include the size of any removable dependencies in installed size'
complete -c pacinfo -l help -d 'Display usage information and exit'

