# paclog
# Autogenerated from man page /usr/share/man/man1/paclog.1.gz
complete -c paclog -l config -d 'Set an alternate configuration file path'
complete -c paclog -l logfile -d 'Set an alternate log file path'
complete -c paclog -l root -d 'Set an alternate installation root'
complete -c paclog -l sysroot -d 'Set an alternate system root.   See pacutils-sysroot\\|(7)'
complete -c paclog -l color -d 'Colorize output'
complete -c paclog -l pkglist -d 'Print the list of installed packages according to the log'
complete -c paclog -l help -d 'Display usage information and exit'
complete -c paclog -l version -d 'Display version information and exit. SS "Filters"'
complete -c paclog -l action -d 'Display package operations'
complete -c paclog -l after -l before -d 'Display entries after/before date'
complete -c paclog -l caller -d 'Display log entries from name.   May be specified multiple times'
complete -c paclog -l commandline -d 'Display pacman-style logged commandline entries'
complete -c paclog -l grep -d 'Display log entries whose message matches regex'
complete -c paclog -l package -d 'Display logged actions affecting pkgname.   May be specified multiple times'

