# pacrepairfile
# Autogenerated from man page /usr/share/man/man1/pacrepairfile.1.gz
complete -c pacrepairfile -l config -d 'Set an alternate configuration file path'
complete -c pacrepairfile -l dbpath -d 'Set an alternate database path'
complete -c pacrepairfile -l root -d 'Set an alternate installation root'
complete -c pacrepairfile -l sysroot -d 'Set an alternate system root.   See pacutils-sysroot\\|(7)'
complete -c pacrepairfile -l quiet -d 'Do not display progress information'
complete -c pacrepairfile -l package -d 'Search pkgname for file properties.   May be specified multiple times'
complete -c pacrepairfile -l help -d 'Display usage information and exit'
complete -c pacrepairfile -l version -d 'Display version information and exit. SS "Fields"'
complete -c pacrepairfile -l gid -d 'Reset file owner group id'
complete -c pacrepairfile -l mode -d 'Reset file permissions'
complete -c pacrepairfile -l mtime -d 'Reset file modification time'

