# pacreport
# Autogenerated from man page /usr/share/man/man1/pacreport.1.gz
complete -c pacreport -l config -d 'Set an alternate pacman configuration file path'
complete -c pacreport -l dbext -d 'Set an alternate sync database extension'
complete -c pacreport -l dbpath -d 'Set an alternate database path'
complete -c pacreport -l root -d 'Set an alternate installation root'
complete -c pacreport -l sysroot -d 'Set an alternate system root.   See pacutils-sysroot\\|(7)'
complete -c pacreport -l cache-dir -d 'Set an alternate cache directory path'
complete -c pacreport -l backups -d 'Search for . pac{save,orig,new} files'
complete -c pacreport -l group -d 'Display any packages in group name that are not currently installed'
complete -c pacreport -l missing-files -d 'Check for missing package files'
complete -c pacreport -l unowned-files -d 'Check for unowned files.   See /etc/pacreport'
complete -c pacreport -l optional-deps -d 'Take optional dependencies into account when listing unneeded packages and de…'
complete -c pacreport -l help -d 'Display usage information and exit'

