# pacrepairdb
# Autogenerated from man page /usr/share/man/man1/pacrepairdb.1.gz
complete -c pacrepairdb -l cachedir -d 'Set an alternate cache directory path'
complete -c pacrepairdb -l config -d 'Set an alternate configuration file path'
complete -c pacrepairdb -l dbonly -d 'Make the changes to the database without actually extracting or removing any …'
complete -c pacrepairdb -l dbpath -d 'Set an alternate database path'
complete -c pacrepairdb -l debug -d 'Display additional debugging information'
complete -c pacrepairdb -l hookdir -d 'Add additional user hook directories'
complete -c pacrepairdb -l logfile -d 'Set an alternate log file path'
complete -c pacrepairdb -l no-confirm -d 'Assume default responses to all prompts'
complete -c pacrepairdb -l no-scriptlet -d 'Do not run package install scripts'
complete -c pacrepairdb -l no-hooks -d 'Do not run transaction hooks'
complete -c pacrepairdb -l no-timeout -d 'Disable low-speed timeouts for downloads'
complete -c pacrepairdb -l print-only -d 'Display the packages to be repaired and the cache packages to be used and exit'
complete -c pacrepairdb -l root -d 'Set an alternate installation root'
complete -c pacrepairdb -l sysroot -d 'Set an alternate system root.   See pacutils-sysroot\\|(7)'
complete -c pacrepairdb -l verbose -d 'Display additional progress information'
complete -c pacrepairdb -l help -d 'Display usage information and exit'

