# pacsync
# Autogenerated from man page /usr/share/man/man1/pacsync.1.gz
complete -c pacsync -l config -d 'Set an alternate configuration file path'
complete -c pacsync -l dbext -d 'Set an alternate sync database extension'
complete -c pacsync -l dbpath -d 'Set an alternate database path'
complete -c pacsync -l logfile -d 'Set an alternate log file path'
complete -c pacsync -l no-timeout -d 'Disable low-speed timeouts for downloads'
complete -c pacsync -l root -d 'Set an alternate installation root'
complete -c pacsync -l sysroot -d 'Set an alternate system root.   See pacutils-sysroot\\|(7)'
complete -c pacsync -l debug -d 'Display additional debugging information'
complete -c pacsync -l updated -d 'Return true only if a database was actually updated'
complete -c pacsync -l force -d 'Update databases even if already up-to-date'
complete -c pacsync -l help -d 'Display usage information and exit'

