# sa1
# Autogenerated from man page /usr/share/man/man8/sa1.8.gz
complete -c sa1 -l boot -d 'This option tells  "sa1 " "that the " "sadc" command should be called without…'
complete -c sa1 -l rotate -d 'RB "Use this option to tell " "sa1 " "to insert a record of statistics to the…'
complete -c sa1 -l sleep -d 'This option tells  sa1  that the  sadc command should insert a comment indica…'

