# sadc
# Autogenerated from man page /usr/share/man/man8/sadc.8.gz
complete -c sadc -s C -d 'When neither the R "interval " "nor the " "count" parameters are specified, t…'
complete -c sadc -s D -d 'RI "Use " "saYYYYMMDD " "instead of " "saDD" as the standard system activity …'
complete -c sadc -s F -d 'RI "The creation of " "outfile" will be forced'
complete -c sadc -s f -d 'fdatasync() will be used to ensure data is written to disk'
complete -c sadc -s L -d 'sadc will try to get an exclusive lock on the  outfile before writing to it o…'
complete -c sadc -s S -d 'Possible keywords are  "DISK" ", " "INT" ", " "IPV6" ", " "POWER" ", " "SNMP"…'
complete -c sadc -s V -d 'Print version number then exit'

