# xbindkeys
# Autogenerated from man page /usr/share/man/man1/xbindkeys.1.gz
complete -c xbindkeys -s d -l defaults -d 'Print a default rc file'
complete -c xbindkeys -s f -l file -d 'Use an alternative rc file'
complete -c xbindkeys -s h -l help -d 'Short help on options plus version/author info'
complete -c xbindkeys -s X -l display -d 'Set X display to use'
complete -c xbindkeys -s v -l verbose -d 'More information on xbindkeys when it runs'
complete -c xbindkeys -s k -l key -d 'Identify one key pressed (useful for configuration)'
complete -c xbindkeys -o mk -l multikey -d 'Identify multi key pressed (useful for configuration)'
complete -c xbindkeys -s g -l geometry -d 'size and position of window with -k|-mk option'
complete -c xbindkeys -s n -l nodaemon -d 'don\'t start as daemon If guile support has not been disabled:'
complete -c xbindkeys -o dg -l defaults-guile -d 'Print a default guile configuration file'
complete -c xbindkeys -o fg -l file-guile -d 'Use an alternative guile configuration file'

